### ISSUE TITLE
Organisation name and About the org needs an update.

### ISSUE THREAD

**Issue by Kaushl2208** [Hypn-OS/About#1]
@hastagAB We decided the name of the org which was different then it is right now. So it needs an update and the details about the organisation, details of the contributors need to be updated ASAP.

**Comment by hastagAB** [comment]
@Kaushl2208 The organization name is correct. It's just that  " Hypnos " is already registered so for the URL it was unavailable that's why I selected "Team Hypnos".

**Comment by Kaushl2208** [comment]
@hastagAB I was talking about the hypn-OS. If you know what I mean with the change. The logo also needs change.

**Comment by hastagAB** [comment]
@Kaushl2208 Renaming Done! :+1: The logo will be updated when it's done.
Thanks!

**Comment by Kaushl2208** [comment]
@hastagAB  The About Section also needs update. Happy to help!! :+1:

**Comment by Kaushl2208** [comment]
@hastagAB  close this issue. I think it been successfully solved.
